### ISSUE TITLE
error when running the hello-vault

### ISSUE THREAD

**Issue by AkhilaDamera** [rwinch/spring-vault-talk#1]
I am getting below error when I ran the hello-vault application:
Exception in thread "main" org.springframework.vault.client.VaultException: Status 404 URI http://localhost:8200/v1/secret/hello-spring-vault: {"request_id":"c5cbac9c-8b38-40a3-a2e7-e7d35555c15b","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,"warnings":["Invalid path for a versioned K/V secrets engine. See the API docs for the appropriate API endpoints to use. If using the Vault CLI, use 'vault kv put' for this operation."],"auth":null}
	at org.springframework.vault.core.VaultTemplate$2.doWithVault(VaultTemplate.java:276)
	at org.springframework.vault.core.VaultTemplate$2.doWithVault(VaultTemplate.java:262)
	at org.springframework.vault.core.VaultTemplate.doWithVault(VaultTemplate.java:192)
	at org.springframework.vault.core.VaultTemplate.write(VaultTemplate.java:262)
	at sample.Main.main(Main.java:28)

I have passed the values using cli and trying to using hello-vault to connect to vault and display the stored results but I am stuck with the above error. Could you please let me know if I need to create vault.cong file for this??
 If so, please let me know what should I include in the config file.

Appreciate your help.

Thanks,

Akhila

**Comment by rwinch** [comment]
Thanks for the report! This sample is over 2 years old and I likely won't have time to update it anytime soon. I'd suggest taking a look at the [Spring Valut site](https://projects.spring.io/spring-vault/) which has it's own [samples](https://github.com/mp911de/spring-cloud-vault-config-samples)
